version: 2

# Group settings to apply to all groups by default, optionally being overridden later
group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^(Approved|:shipit:|:\+1:)'
    reject_regex: '^(Rejected|:-1:)'

groups:
  pullapprove-admins:
    conditions:
      files:
        - ".pullapprove.yml"
    required: 1
    users:
      - iclanton
      - nickpape-msft
      - pgonzal
      - qz2017
      - patmill

  rush-approvers:
    conditions:
      files:
        - "apps/rush/*"
        - "apps/rush-lib/*"
    required: 1
    users:
      - iclanton
      - nickpape-msft
      - pgonzal
      - qz2017

  gcb-approvers:
    conditions:
      files:
        - "core-build/*"
        - "libraries/*"
        - "webpack/*"
    required: 1
    users:
      - iclanton
      - nickpape-msft
      - pgonzal
      - qz2017

  load-themed-styles-approvers:
    conditions:
      files:
        - "libraries/load-themed-styles/*"
    required: 1
    users:
      - iclanton
      - nickpape-msft
      - pgonzal
      - qz2017
      - dzearing
