version: 2

# Group settings to apply to all groups by default, optionally being overridden later
group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^(Approved|:shipit:|:\+1:)'
    reject_regex: '^(Rejected|:-1:)'

groups:
  pullapprove-admins:
    conditions:
      files:
        - ".pullapprove.yml"
    required: 1
    users:
      - iclanton
      - nickpape-msft
      - pgonzal
      - qz2017
      - patmill

  rush-approvers:
    conditions:
      files:
        - "rush/*"
    required: 1
    users:
      - iclanton
      - nickpape-msft
      - pgonzal
      - qz2017

  api-extractor-approvers:
    conditions:
      files:
        - "api-extractor/*"
    required: 1
    users:
      - pgonzal
      - dgaeta

  gcb-approvers:
    conditions:
      files:
        - "gulp-core-build/*"
        - "gulp-core-build-karma/*"
        - "gulp-core-build-mocha/*"
        - "gulp-core-build-sass/*"
        - "gulp-core-build-serve/*"
        - "gulp-core-build-typescript/*"
        - "gulp-core-build-webpack/*"
    required: 1
    users:
      - iclanton
      - nickpape-msft
      - pgonzal
      - qz2017
