language: node_js
node_js:
- '4.2'
before_script:
- npm install -g gulp
script: gulp
deploy:
  skip_cleanup: true
  provider: npm
  email: odspnpm@microsoft.com
  api_key:
    secure: iHYu/oXrJL0yV1XE/u1Jq+f41FeTb7zFkLdMp1Mjc6w2EEzuYXl+iy6FFcQmpuLASlWTkraDbEAHGnKyBKajiwg0aE9dsjcYZNVmpClQAObypze9IrDu8hqog2R8lpsybaWyQ8kY97Kf5TnUBSk4aNXsXX73b5VlsMswVPOZoo5IT38DVpELCQrzKCWHFcEswGSGI0RTVAz+B2d20uT8kyyRC67jJEv00ARqw2/15trShHHmU4KHPBY//uLGCcYnnyFL4rLE4Hf5/a/bjnHM4GFRysLUr1J1NamMH5pMfJ/bP++SW8doKbPnXKpKLkVTYQHgGS0d2VcNbnk3xhApewY2F/MNz4g0nP8Cnt1p/ALZitIcp+/VJGnRKXFFdrerLr8PhaJEmEyrs74wxUsD/vKKLjZce2SG07aG4ytzaCuYFoxMaXEZvUFM6EwG5wOTHOkgwarnUwhCRzeJR/XDkxzYD+yuiqDoEoaPYfBn7RN9oBrQnYAz1h2u696BYdUGcquy+Zlk4APdY4VfbRSW7QsxqIJqh16cHYfPGAq1cIeBssdQXqS+WdHfRQ/xAZCtlVj2sRCCNJsc32Z6lWuz73yqWICrQ8wzBEk4Me7FfCgXFdcUPopOJxY1AeXawX2vTYhQZlO7lKM7rsjHwB4Q2nm+AmPEEUSeVJfeQCkFh7Q=
  on:
    tags: true
    repo: microsoft/node-library-build
