language: node_js
node_js:
- '4.2'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: npm
  email: odspnpm@microsoft.com
  skip_cleanup: true
  on:
    tags: true
    repo: Microsoft/gulp-core-build
  api_key:
    secure: Geb2quQmb5eXnAC+dj2LQDdKKQn1U9mpiDv6upLmO9v4qBJQITjPu6uNomwgd5VkkaWuuSbSf4fHeBVBWgGKLYWyeFKW2fEZ0LKG0/wnsbRr4rF8FpJi00uBt1hFBzLBhHGc7OtQ5pUupJQ1lf/vDFOLxZ8y5F2oL8CVWhDESOnzL0pc4vTL7YxHBAYI5FvVKPl7STRQmXbVKqNtkCm9ejLVH31ATYGUJQYP7MaSYdhf0JR3pWNrIgQGwtHf7HpPDN3UGoYHAmAl6lZ7bfYCDn5rCO20OhgMJ5oViIUy/MM/leB/TX/EGYUp0huwxKQ/k3+W00Tx9Q9Z6gCN4cVCPU6McJqaz3VW6XFoRC+OfAHmxD4U2dlPtsXalxsqdhhqvsFDWX+07F378zyacbotVoFExIadNZ9aoWxjTjPwp4Fow/A9IeCMGQzukrGspQl7egBB3On9ouy6k3loayi3Bsmmxp6ryWByykRZiDH4CGg3Z8J4QVYDel7JykXP2zf3HW3GvSwdAUd9ek7tf7/mJ6nthS4VB+F8aM2O8aPNs7N5V8vnw6NVVD9Ti1UD0WaEdDCuDrIkVWr0R9ATY5aooIYALHJqNhz0lg+xPvnBAm1IBKBPQ+DvQhknsNcU0GsdEXpliMQrA/Z8D7NWYaP2jUCPiSyUg9lAjvX8HOwZl+k=

