language: node_js
node_js:
- '4.2'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: npm
  email: dzearing@hotmail.com
  api_key:
    secure: HCFCqqNS/IGJmjcDCWS+w5q5RuXN5yuWoct+QDUwH8eMfuF96E3CPHGQoPd1+61wib3SBztOJr+NfuSrzLEzONbc5AvpK68pxPTgW5dQv42mC8Rb36J6c6QmNmx6vbQcy8is5eO8E07mCuNCN8BX62O3a2lQjXYXAQLZ9ARdOM/5PDwGWEgmql0yu2aXOdJZVVrLlEb5nfxaI6ccMf5IiTz5BsXrVcVhBpRP/jFg6hmLvSI7h0S6JMKzjklskK1gijvK2M2OtgNIOyPlmZeXQfVrrN6JqmjDpXoaKM1aMWh8lZC0JkewSDmwjFjzRzGQjhskQHjbBnRkR2SYmpi90h0R7me0xF2ZPuQd4RLYX55rM3o0eztfVcrxFN2W5QR4o9WcElj46V2K0lytcMgJjLbwuIF2FkNgr1nR9SWakehAWalWlFLmURhuf+CtBs86/K+IyMbpwrrB9h1Xy2riR2JdWDXL07YxtcK68iMtntx3pJHJa8z1yDIsxJVFR4wxWm2ADkfIvOcSGDdV4z5Y6hhSzN3hvJNXr1PvsPK8axZo5RQfY0JFkGPXPINE8JzoIAyhA7cJikr7xT91wDwvOY1cEcWj7boo+YxQ74pNNjeW5pCmU2ZhQJrcRWHx447UwU68LZaGJbqYGqGhEMIZpGgBw4LA5Gy1BW8Q9x9dc9E=
  on:
    tags: true
    repo: dzearing/gulp-core-build-mocha
