language: node_js
node_js:
- '4.2'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: npm
  email: odspnpm@microsoft.com
  api_key:
    secure: Dek0eGwt3fsIu3Ag10MfPiHnru0wGcPXKhU3GcbR69rokPuPc9gflGUcmNfNjJBPnqVit3O/Q9Mm83wC5n6VFYEvLR7ctcrMk5FQwRLfJKtQ8ao0mWcpPJr2645kDKO1h2dc6pLtRwRGTlnwitLM/SBebnfIzgQhcH77Rehqk0NhddjWh/Up1+hCxxeBvC8LhuO5usVMlXnX0fCbHQ6ConeH//hE/gQ4Ph5gGEAazi8ok5mBgqNQPVgBfuy82W6Ibo5ZLr/kRLciD9YPsZQJeZfjme49KTqej+uFuDOM6EuKPEXDMdN1bOmzirEmAuq2U+GdI5EfFy6Xtz+r2xeCeh04LtK/7rNo1w4HGN2RNSCYpvWc5C8XHVmtZ514wn9+X2X9vpB/Yae8Q3NoVVRKaZQ5Z+yjVQ4TivwwuCmJRKIO1pAzcqepY4Q9xpeV5GZ+z3vlY3Fl0I5o4DOPCd22a5V+iY24VFSo5HzRwsgnH9Eq7v3wgHgVo6CxXoo/ZcyY8uxDmuIlDoQxbMmEmysdPQ4oxtIW/h0+qkfKWVkUW6oLNFkWE0NB1+/zVudaY1rBC0oBWOTLlA064ycAh4Od1UZDagx1oxh4NQ6Qgyf1SAVxARfpBoCBAKPPJCPcHzyw4s+c47LvOj1gDQTUq7UmEpj3h1EzbA2BJjCtZfawoTo=
  on:
    tags: true
    repo: Microsoft/gulp-core-build-mocha
