language: node_js
node_js:
- '4.2'
before_script:
- npm install -g gulp
script: gulp
deploy:
  skip_cleanup: true
  provider: npm
  email: odspnpm@microsoft.com
  api_key:
    secure: w+d8ZqV3/KP1iB965pcHfhxhTDqLTm6tz760wTBd10F8fC0qtdGr+F5ioPH1ellPgUzK087+Bi+j55x8PzT4DIp9oJMC5cjIuKun22mzLVVlcL4Vc6ZToHCNHzWMBazSN1RBo1EA26AoKPUfPF0ZkWFunYkgt0wKb9TnQr1NdqtQUHgqKvMOv/tlSJnBvriv77x1vcVvOrwE7HZ4m0QYZkcCz64WU5fANmnEI4+VBoXq/OzwuQQ2tMa8ZNzjK+iWnDrl31wKwwpmNdJLX4BgynTuLvTY0roSASnvmvfMUWSRM3rvGB9zJ08Rc+j3gQHY8DQ5Exqx2HOS9s3uYTpgVfm6UEM7hEWcmf/hb9PwtbLKRDXJPIp9LXWLfHm25AmQstmofhF1Rict8k0JyxtLsFgGkjXL5UA7Aom9rAz0nHIw4NkV14HTm64Dgj61oGzAz0f5WZvoU7nJ05J50Wy3x/gisU1X8aQkO10qDWOq4UGwQYvSiExmZqJm7IZaGYhgBYLxasH+On8YB1Vp2H48i30lHAV2UwVrQ/+Gni/UxKJWU7Iuc0rIPgUzsmKFh+jPwN3/8WUtiFScruIdZgjKsAIDDqXhYBOq5b3WlqFBXaeuiWQwr1xVyYVcGD1Gy1UwF3aCBAcag6mbDig5LzGSymOzWh9KKMjE61Z201COdzE=
  on:
    tags: true
    repo: Microsoft/web-library-build
