language: node_js
node_js:
- '4.2'
before_script:
- npm install -g gulp
script: gulp
deploy:
  skip_cleanup: true
  provider: npm
  email: odspnpm@microsoft.com
  api_key:
    secure: vVX/oaVTkJOLQVIgbp6ZgFzz9rSbrI3Ke+tgL4m2bL7aZMfuZcpik6f0GjWe2EtesQ14VZughEoDrdoEGWUE87xf2k/BSMyS1f7oG2jlQ7hNHgAjSbV3mGu7GN6bG5MctNdy1QudgcjYUymNTzb+RhLAXwiKdUvPZ8VJiaeYnF6N3f+Lfmd/5/7C/GgaVFCZ89aF/fixr6HLjrWRXZ0D5VJoWNzMniGUCNs8bBem9S9SIKtcuydy4GX3I3PUe0Md5bS/cqdlMcxNcoV5l1kUiOf+c/knGJiDzfMHq5ao/PpDF+jJXisqf0UXfrkm/r6WlhPkZGYNYXtOZ76DpeXza8Ba3uj2G+Wyr0szJl+WN+MyTqEtcX5bVgjIzOqPgF1QMcmzRnnXDa9LAimW5/Ku7qhtuVGCIbGBThEv5dIhEvSmZj/JYDmyRXvs4nLMfJSevZYKw4Ui/RwJ1Ki+3EWBGA73ybmYI9hV/dZgxlRNm7q3W6q9K8V/kQjFAdL4kU0dPT8qQxKcnZHRr7s8T95Gs/ykkXHVNGD9lR7diuUgxCOuYXQk9ie+gQ6aCLa1p0BT9h597kabpgtCjjg0aOv9FgP7HskqaKMnA7rpxXpGchCFMfU70b4fEdW0jG0t+AOWd+xW2eq0vV/zT613v2CAwdTA9fxZGN2cqQUL/MDQKKA=
  on:
    tags: true
    repo: Microsoft/gulp-core-build
