parameters:
  - name: VersionPolicyName
    type: string
  - name: BranchName
    type: string
    default: $(Build.SourceBranchName)

steps:
  - task: EsrpRelease@7
    inputs:
      connectedservicename: 'odsp-web-esrp'
      keyvaultname: 'odsp-web-esrp'
      authcertname: 'esrp-cert'
      signcertname: 'esrp-sign'
      clientid: 'be2088dc-be24-46c8-b0b1-aa555603f375'
      intent: 'PackageDistribution'
      contenttype: 'npm'
      folderlocation: '$(System.DefaultWorkingDirectory)/ts/out/pkg'
      waitforreleasecompletion: true
      owners: 'odspxfun@microsoft.com'
      approvers: 'odspxfun@microsoft.com'
      serviceendpointurl: 'https://api.esrp.microsoft.com'
      mainpublisher: 'ESRPRELPACMAN'
      domaintenantid: 'cdc5aeea-15c5-4db6-b079-fcadd2505dc2'
