name: Documentation Tickets

on: [pull_request]

jobs:
  file-tickets:
    name: File Tickets
    runs-on: ubuntu-latest
    steps:
      - name: Use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Parse PR body
        run: |
          cat <<-"EOF" > event.json
          ${{ toJson(github.event) }}
          EOF

          cat <<-"EOF" | node
          const fs = require('fs');

          const EVENT_FILE = 'event.json';
          const RESULT_FILE = 'issue.md';
          const DELIMITER = '## Impacted documentation';

          const event = JSON.parse(fs.readFileSync(EVENT_FILE, 'utf8'));
          const strippedBody = event.pull_request.body.replace(/<!-+(.|\r|\n)+?-+>/g, '');
          const delimIndex = strippedBody.indexOf(DELIMITER);

          if (delimIndex < 0) {
            console.log('No documentation tasks detected -- skipping doc ticket.');
            process.exit(0);
          }

          const delimBody = strippedBody.substring(delimIndex + DELIMITER.length).trim();

          if (delimBody.length === 0) {
            console.log('No documentation tasks detected -- skipping doc ticket.');
            process.exit(0);
          }

          const quotedBody = delimBody.split('\n').map(line => `> ${line}`).join('\n');
          fs.writeFileSync(RESULT_FILE, [
            '### Summary',
            '',
            'Follow up on documentation tasks from ' + event.pull_request.html_url + '.',
            '',
            '### Details',
            '',
            'This ticket was generated automatically. Suggested documentation updates:',
            '',
            quotedBody,
            ''
          ].join('\n'), 'utf8');

          EOF

          if [ -f issue.md ]; then
            echo "FILE_TICKET=1" >> $GITHUB_ENV
          fi
      - name: File ticket
        if: ${{ env.FILE_TICKET == '1' }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          repository: https://github.com/elliot-nelson/rushstack-websites
          title: '[doc] ${{ github.event.pull_request.title }}'
          content-filepath: ./issue.md
          labels: |
            automated
