name: Documentation Followup

on: [pull_request]

jobs:
  file-ticket:
    name: File Ticket
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Hello
          echo "${{github.event.pull_request}}"
          echo "${{toJson(github.event.pull_request.body)}}"
          echo "${{toJson(github.event.pull_request.html_url)}}"
          echo Done
