name: Documentation Followup

on: [pull_request]

jobs:
  file-ticket:
    name: File Ticket
    runs-on: ubuntu-latest
    steps:
      - name: Use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Parse PR body
        run: |
          cat <<-"EOF" > event.json
          ${{ toJson(github.event) }}
          EOF

          echo event writen

          cat <<-"EOF" | node
          const fs = require('fs');

          const EVENT_FILE = 'event.json';
          const RESULT_FILE = 'result.env';
          const DELIMITER = '## Impacted documentation';

          const event = JSON.parse(fs.readFileSync(EVENT_FILE, 'utf8'));
          const strippedBody = event.pull_request.body.replace(/<!-+(.|\n)+?-+>/g, '');
          const delimIndex = strippedBody.indexOf(DELIMITER);

          if (delimIndex < 0) {
            console.log('No documentation tasks detected -- skipping doc ticket.');
            process.exit(0);
          }

          const delimBody = strippedBody.substring(delimIndex + DELIMITER.length).trim();

          if (delimBody.length === 0) {
            console.log('No documentation tasks detected -- skipping doc ticket.');
            process.exit(0);
          }

          const quotedBody = delimBody.split('\n').map(line => `> ${line}`).join('\n');
          fs.writeFileSync(RESULT_FILE, [
            'POST_DOC_BODY<<EOF',
            quotedBody,
            'EOF',
            'POST_DOC_HTML_URL=' + event.pull_request.html_url
          ].join('\n'), 'utf8');

          EOF
      - name: File ticket
        if: ${{ env.POST_DOC_BODY != null }}
        run: |
          echo "Great! ${{ env.POST_DOC_HTML_URL }}"
          echo "Great! ${{ env.POST_DOC_BODY }}"
